# Generated by Django 5.0.2 on 2024-04-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentlyWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('episode_number', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('aired', models.DateTimeField()),
                ('filler', models.BooleanField()),
                ('recap', models.BooleanField()),
                ('mal_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('mal_id', models.IntegerField(unique=True)),
                ('episode_count', models.IntegerField()),
                ('image', models.ImageField(default='anime_pictures/default.jpg', upload_to='anime_pictures')),
                ('airing', models.BooleanField(blank=True, null=True)),
                ('aired_from', models.DateTimeField(blank=True, null=True)),
                ('aired_to', models.DateTimeField(blank=True, null=True)),
                ('age_rating', models.CharField(max_length=10, null=True)),
                ('mal_score', models.FloatField(blank=True, null=True)),
                ('mal_rank', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('broadcasting_time', models.CharField(blank=True, max_length=20, null=True)),
                ('studio', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.animetype')),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
            ],
        ),
    ]
